USE QLDeTai;
GO

-- Q35. Cho biết mức lương cao nhất của các giảng viên. -- 
SElECT MAX(GV.LUONG) AS MucLuongCaoNhat
FROM GIAOVIEN AS GV

-- Q36. Cho biết những giáo viên có lương lớn nhất.
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.LUONG = (SELECT MAX(GIAOVIEN.LUONG)
					FROM GIAOVIEN)

-- Q37. Cho biết lương cao nhất trong bộ môn “HTTT”.
/*SELECT MAX(GV.LUONG) AS LuongCaoNhat
FROM GIAOVIEN AS GV
WHERE GV.MABM = 'HTTT' */
SELECT MAX(GV.LUONG) AS HTTT_MaxLuong
FROM (SELECT GIAOVIEN.* 
		FROM GIAOVIEN
		WHERE GIAOVIEN.MABM = 'HTTT') AS GV

-- Q38. Cho biết tên giáo viên lớn tuổi nhất của bộ môn Hệ thống thông tin.
SELECT GV.HoTen
FROM GIAOVIEN AS GV
WHERE YEAR(GV.NGAYSINH) = (SELECT MIN(YEAR(GIAOVIEN.NGAYSINH))
							FROM GIAOVIEN JOIN BOMON ON (GIAOVIEN.MABM = BOMON.MABM)
							WHERE BOMON.TENBM = N'Hệ thống thông tin')

-- Q39. Cho biết tên giáo viên nhỏ tuổi nhất khoa Công nghệ thông tin.
SELECT GV.HOTEN
FROM GIAOVIEN AS GV 
WHERE YEAR(GV.NGAYSINH) = (SELECT MAX(YEAR(GIAOVIEN.NGAYSINH))
							FROM GIAOVIEN JOIN (BOMON JOIN KHOA ON (BOMON.MAKHOA = KHOA.MAKHOA)) ON (GIAOVIEN.MABM = BOMON.MABM)
							WHERE KHOA.TENKHOA = N'Công nghệ thông tin')

-- Q40. Cho biết tên giáo viên và tên khoa của giáo viên có lương cao nhất.
SELECT  GV.HOTEN, K.TENKHOA
FROM GIAOVIEN AS GV JOIN (BOMON AS BM JOIN KHOA AS K ON (K.MAKHOA = BM.MAKHOA)) ON (GV.MABM = BM.MABM)
WHERE GV.LUONG = (SELECT MAX(GIAOVIEN.LUONG)
					FROM GIAOVIEN)

-- Q41. Cho biết những giáo viên có lương lớn nhất trong bộ môn của họ.
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.LUONG = (SELECT MAX(GIAOVIEN.LUONG) 
					FROM GIAOVIEN	
					WHERE GV.MABM = GIAOVIEN.MABM
					GROUP BY GIAOVIEN.MABM )

-- Q42. Cho biết tên những đề tài mà giáo viên Nguyễn Hoài An chưa tham gia.
SELECT DT.TENDT
FROM DETAI AS DT
WHERE DT.MADT NOT IN ( SELECT DISTINCT THAMGIADT.MADT
						FROM DETAI JOIN (THAMGIADT JOIN GIAOVIEN ON (GIAOVIEN.MAGV = THAMGIADT.MAGV)) ON DETAI.MADT = THAMGIADT.MADT
						WHERE GIAOVIEN.HOTEN = N'Nguyễn Hoài An' )

-- Q43. Cho biết những đề tài mà giáo viên Nguyễn Hoài An chưa tham gia. Xuất ra tên đề tài, tên người chủ nhiệm đề tài.
SELECT DT.TENDT, GV.HOTEN AS GVCNDT_HOTEN
FROM DETAI AS DT JOIN GIAOVIEN AS GV ON (GV.MAGV = DT.GVCNDT)
WHERE DT.MADT NOT IN ( SELECT DISTINCT THAMGIADT.MADT
						FROM DETAI JOIN (THAMGIADT JOIN GIAOVIEN ON (GIAOVIEN.MAGV = THAMGIADT.MAGV)) ON DETAI.MADT = THAMGIADT.MADT
						WHERE GIAOVIEN.HOTEN = N'Nguyễn Hoài An' )

-- Q44. Cho biết tên những giáo viên khoa Công nghệ thông tin mà chưa tham gia đề tài nào.
SELECT GV.HOTEN
FROM KHOA JOIN (BOMON AS BM JOIN GIAOVIEN AS GV ON (GV.MABM = BM.MABM)) ON KHOA.MAKHOA = BM.MAKHOA
WHERE KHOA.TENKHOA = N'Công nghệ thông tin' AND GV.MAGV NOT IN (SELECT DISTINCT TGDT.MAGV
						FROM THAMGIADT AS TGDT JOIN GIAOVIEN ON (TGDT.MAGV = GIAOVIEN.MAGV) ) 

-- Q45. Tìm những giáo viên không tham gia bất kỳ đề tài nào
SELECT GV.* 
FROM GIAOVIEN AS GV
WHERE GV.MAGV NOT IN (SELECT TGDT.MAGV	
						FROM THAMGIADT AS TGDT JOIN GIAOVIEN ON (GIAOVIEN.MAGV = TGDT.MAGV))

-- Q46. Cho biết giáo viên có lương lớn hơn lương của giáo viên “Nguyễn Hoài An”
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.LUONG > (SELECT GIAOVIEN.LUONG	
					FROM GIAOVIEN
					WHERE GIAOVIEN.HOTEN = N'Nguyễn Hoài An')

-- Q47. Tìm những trưởng bộ môn tham gia tối thiểu 1 đề tài
SELECT GV.*
FROM BOMON AS BM JOIN GIAOVIEN AS GV ON (GV.MAGV = BM.TRUONGBM)
WHERE BM.TRUONGBM = ANY (SELECT TGDT.MAGV
						FROM THAMGIADT AS TGDT)

-- Q48. Tìm giáo viên trùng tên và cùng giới tính với giáo viên khác trong cùng bộ môn
SELECT GV.*
FROM GIAOVIEN AS GV 
WHERE GV.MABM = (SELECT GIAOVIEN.MABM
				FROM GIAOVIEN	
				WHERE GIAOVIEN.HOTEN = GV.HOTEN AND GV.PHAI = GIAOVIEN.PHAI AND GV.MABM = GIAOVIEN.MABM AND GV.MAGV != GIAOVIEN.MAGV)

-- Q49. Tìm những giáo viên có lương lớn hơn lương của ít nhất một giáo viên bộ môn “Công nghệ phần mềm”
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.LUONG > ANY (SELECT GIAOVIEN.LUONG
						FROM GIAOVIEN JOIN BOMON ON (GIAOVIEN.MABM = BOMON.MABM)
						WHERE BOMON.TENBM = N'Công nghệ phần mềm')

-- Q50. Tìm những giáo viên có lương lớn hơn lương của tất cả giáo viên thuộc bộ môn “Hệ thống thông tin”
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.LUONG > ALL (SELECT GIAOVIEN.LUONG
						FROM GIAOVIEN JOIN BOMON ON (GIAOVIEN.MABM = BOMON.MABM)
						WHERE BOMON.TENBM = N'Hệ thống thông tin')

-- Q51. Cho biết tên khoa có đông giáo viên nhất
SELECT KHOA.TENKHOA
FROM GIAOVIEN JOIN BOMON ON (GIAOVIEN.MABM = BOMON.MABM) JOIN KHOA ON (KHOA.MAKHOA = BOMON.MAKHOA)
GROUP BY KHOA.MAKHOA, KHOA.TENKHOA
HAVING COUNT(*) = (SELECT MAX(SLGV)
						FROM (SELECT COUNT(GIAOVIEN.MAGV) AS SLGV, KHOA.MAKHOA
								FROM GIAOVIEN JOIN BOMON ON (GIAOVIEN.MABM = BOMON.MABM) JOIN KHOA ON (KHOA.MAKHOA = BOMON.MAKHOA)
								GROUP BY KHOA.MAKHOA) AS T)

 -- Q52. Cho biết họ tên giáo viên chủ nhiệm nhiều đề tài nhất
 SELECT GV.HOTEN
 FROM GIAOVIEN AS GV JOIN DETAI AS DT ON (GV.MAGV = DT.GVCNDT)
 GROUP BY DT.GVCNDT, GV.HOTEN
 HAVING COUNT(DT.MADT) = ( SELECT MAX(SLDeTai)
							FROM (SELECT COUNT(DT.MADT) AS SLDeTai
									FROM DETAI AS DT
									GROUP BY DT.GVCNDT	) AS T)

-- Q53. Cho biết mã bộ môn có nhiều giáo viên nhất
SELECT GV.MABM
FROM GIAOVIEN AS GV
GROUP BY GV.MABM
HAVING COUNT(GV.MAGV) = ( SELECT MAX(SLGiaoVien)
							FROM (SELECT COUNT(GIAOVIEN.MAGV) AS SLGiaoVien
									FROM GIAOVIEN
									GROUP BY GIAOVIEN.MABM) AS T)

-- Q54. Cho biết tên giáo viên và tên bộ môn của giáo viên tham gia nhiều đề tài nhất.
SELECT GV.HOTEN, BM.TENBM
FROM THAMGIADT AS TGDT JOIN GIAOVIEN AS GV ON (GV.MAGV = TGDT.MAGV) JOIN BOMON AS BM ON (BM.MABM = GV.MABM)
GROUP BY TGDT.MAGV, GV.HOTEN, BM.TENBM 
HAVING COUNT(DISTINCT TGDT.MADT) = (SELECT MAX(SLDeTai)
									FROM (SELECT COUNT ( DISTINCT TG.MADT) AS SLDeTai
											FROM THAMGIADT AS TG
											GROUP BY TG.MAGV) AS T)

-- Q55. Cho biết tên giáo viên tham gia nhiều đề tài nhất của bộ môn HTTT.
SELECT GV.HOTEN
FROM GIAOVIEN AS GV JOIN THAMGIADT AS TGDT ON (TGDT.MAGV = GV.MAGV)
WHERE GV.MABM = 'HTTT'
GROUP BY GV.HOTEN, TGDT.MAGV, GV.MABM
HAVING COUNT(DISTINCT TGDT.MADT) = (SELECT MAX (SLDeTai)
									FROM (SELECT COUNT(DISTINCT TG.MADT) AS SLDeTai
											FROM THAMGIADT AS TG JOIN GIAOVIEN AS GV2 ON (GV2.MAGV = TG.MAGV)
											WHERE GV2.MABM = GV.MABM
											GROUP BY TG.MAGV) AS T)

-- Q56. Cho biết tên giáo viên và tên bộ môn của giáo viên có nhiều người thân nhất.
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN AS GV JOIN BOMON AS BM ON (BM.MABM = GV.MABM) JOIN NGUOITHAN NT ON (NT.MAGV = GV.MAGV)
GROUP BY GV.HOTEN, BM.TENBM, NT.MAGV
HAVING COUNT(*) >= ALL (SELECT COUNT (*) AS SLNguoiThan
						FROM GIAOVIEN JOIN NGUOITHAN ON (NGUOITHAN.MAGV = GIAOVIEN.MAGV)
						GROUP BY NGUOITHAN.MAGV)


-- Q57. Cho biết tên trưởng bộ môn mà chủ nhiệm nhiều đề tài nhất.						
SELECT GV.HOTEN
FROM GIAOVIEN AS GV JOIN BOMON AS BM ON (GV.MAGV = BM.TRUONGBM) JOIN DETAI AS DT ON (DT.GVCNDT = BM.TRUONGBM)
GROUP BY BM.TRUONGBM, GV.HOTEN
HAVING COUNT(*) >= ALL (SELECT COUNT(*) AS SLDT
						FROM BOMON JOIN DETAI ON (BOMON.TRUONGBM = DETAI.GVCNDT)
						GROUP BY BOMON.TRUONGBM)






