USE QLDeTai; 
GO

-- Q58. Cho biết tên giáo viên nào mà tham gia đề tài đủ tất cả các chủ đề.

--EXCEPT
SELECT DISTINCT GV.HOTEN
FROM  THAMGIADT AS TG1 JOIN DETAI AS DT ON (DT.MADT = TG1.MADT) 
	JOIN GIAOVIEN AS GV ON(GV.MAGV = TG1.MAGV)
WHERE NOT EXISTS ( 
				  SELECT CD.MACD FROM CHUDE AS CD
			EXCEPT 
				  SELECT DT2.MACD
					FROM  THAMGIADT AS TG2 JOIN DETAI AS DT2 ON (DT2.MADT = TG2.MADT)  
					WHERE TG2.MAGV = TG1.MAGV)

-- NOT EXIST
SELECT DISTINCT GV.HOTEN
FROM THAMGIADT AS TG1 JOIN DETAI AS DT1 ON (DT1.MADT = TG1.MADT) 
	JOIN GIAOVIEN AS GV ON (GV.MAGV = TG1.MAGV)
WHERE NOT EXISTS (
					SELECT CD.MACD 
					FROM CHUDE AS CD
					WHERE NOT EXISTS (
										SELECT DT2.MACD
										FROM THAMGIADT AS TG2 JOIN DETAI AS DT2 ON (DT2.MADT = TG2.MADT) 
										WHERE CD.MACD = DT2.MACD AND
											  TG2.MAGV = TG1.MAGV))

-- COUNT
SELECT DISTINCT GV.HOTEN
FROM THAMGIADT AS TG1 JOIN DETAI AS DT1 ON (DT1.MADT = TG1.MADT) JOIN GIAOVIEN AS GV ON (GV.MAGV = TG1.MAGV)
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT (DISTINCT DT1.MACD) = (SELECT COUNT (CD.MACD)
									FROM CHUDE AS CD)

-- Q59. Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn HTTT tham gia.
-- bị chia: THAMGIADT

-- EXCEPT
SELECT DISTINCT DT.TENDT
FROM DETAI AS DT JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT.MADT)
WHERE NOT EXISTS ( SELECT GV.MAGV
					FROM GIAOVIEN AS GV
					WHERE GV.MABM = 'HTTT'
				EXCEPT 
				 ( SELECT TG2.MAGV
					FROM THAMGIADT AS TG2
					WHERE TG2.MADT = TG1.MADT))

-- NOT EXIST
SELECT DISTINCT DT.TENDT
FROM DETAI AS DT JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT.MADT)
WHERE NOT EXISTS ( SELECT GV.MAGV
					FROM GIAOVIEN AS GV
					WHERE GV.MABM = 'HTTT' 
						AND NOT EXISTS (  SELECT TG2.MAGV
											FROM THAMGIADT AS TG2
											WHERE TG2.MADT = TG1.MADT AND TG2.MAGV = GV.MAGV))

-- COUNT
SELECT DT.TENDT
FROM DETAI AS DT JOIN THAMGIADT AS TG1 ON (TG1.MADT=DT.MADT) 
	JOIN GIAOVIEN AS GV ON (GV.MAGV = TG1.MAGV)
WHERE GV.MABM = 'HTTT'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT TG1.MAGV) = (SELECT COUNT(MAGV) FROM GIAOVIEN WHERE MABM = 'HTTT')

-- Q60. Cho biết tên đề tài có tất cả giảng viên bộ môn “Hệ thống thông tin” tham gia

-- EXCEPT  
SELECT DISTINCT DT.TENDT
FROM DETAI AS DT JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT.MADT)
WHERE NOT EXISTS (SELECT GV.MAGV
					FROM GIAOVIEN AS GV JOIN BOMON AS BM ON (BM.MABM = GV.MABM)
					WHERE BM.TENBM = N'Hệ thống thông tin'
				EXCEPT
				  SELECT TG2.MAGV
					FROM THAMGIADT AS TG2 
					WHERE TG2.MADT = TG1.MADT)

-- NOT EXISTS
SELECT DISTINCT DT.TENDT
FROM DETAI AS DT JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT.MADT)
WHERE NOT EXISTS (SELECT GV.MAGV
					FROM GIAOVIEN AS GV JOIN BOMON AS BM ON (BM.MABM = GV.MABM)
					WHERE BM.TENBM = N'Hệ thống thông tin' 
				AND NOT EXISTS(
								SELECT TG2.MAGV
								FROM THAMGIADT AS TG2 
								WHERE TG2.MADT = TG1.MADT AND TG2.MAGV = GV.MAGV))
-- COUNT 
SELECT DT.TENDT
FROM DETAI AS DT JOIN THAMGIADT AS TG1 ON (TG1.MADT=DT.MADT) JOIN GIAOVIEN AS GV ON (GV.MAGV = TG1.MAGV) JOIN BOMON AS BM ON (GV.MABM = BM.MABM)
WHERE BM.TENBM = N'Hệ thống thông tin'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT TG1.MAGV) = (SELECT COUNT(MAGV) 
									FROM GIAOVIEN JOIN BOMON ON (GIAOVIEN.MABM = BOMON.MABM)
									WHERE TENBM = N'Hệ thống thông tin')	

-- Q61. Cho biết giáo viên nào đã tham gia tất cả các đề tài có mã chủ đề là QLGD.

-- EXCEPT
SELECT DISTINCT GV.*
FROM GIAOVIEN AS GV JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV.MAGV) 
	JOIN DETAI AS DT ON (DT.MADT = TG1.MADT) 
WHERE DT.MACD ='QLGD' AND NOT EXISTS ( SELECT DT2.MADT
										FROM DETAI AS DT2
										WHERE DT2.MACD = 'QLGD'
									EXCEPT 
									   SELECT DT3.MADT
										FROM THAMGIADT AS TG2 JOIN DETAI AS DT3 ON (DT3.MADT = TG2.MADT)
										WHERE TG2.MAGV = TG1.MAGV)

-- NOT EXISTS
SELECT DISTINCT GV.*
FROM GIAOVIEN AS GV JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV.MAGV)
	JOIN DETAI AS DT ON (DT.MADT = TG1.MADT)
WHERE DT.MACD = 'QLGD' 
	AND NOT EXISTS (SELECT DT2.MADT
					FROM DETAI AS DT2
					WHERE DT2.MACD = 'QLGD' 
						AND NOT EXISTS (SELECT DT3.MADT
										FROM DETAI AS DT3 JOIN THAMGIADT AS TG2 ON (TG2.MADT = DT3.MADT)
										WHERE DT3.MADT = DT2.MADT AND TG2.MAGV = TG1.MAGV))
																			
-- COUNT 
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG1 ON (TG1.MAGV = GV.MAGV) 
	JOIN DETAI DT ON (DT.MADT = TG1.MADT)
WHERE DT.MACD = 'QLGD' 
GROUP BY GV.MAGV, GV.HOTEN, DT.MACD
HAVING COUNT (DISTINCT TG1.MADT) = (SELECT COUNT(DT2.MACD)
									FROM DETAI AS DT2 
									WHERE DT2.MACD = 'QLGD')
	
-- Q62. Cho biết tên giáo viên nào tham gia tất cả các đề tài mà giáo viên Trần Trà Hương đã tham gia.
-- chia: de tai gv TTH tham gia
-- EXCEPT
SELECT DISTINCT GV.HOTEN
FROM DETAI AS DT JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT.MADT)
	JOIN GIAOVIEN AS GV ON (GV.MAGV = TG1.MAGV)
WHERE GV.HOTEN != N'Trần Trà Hương' AND NOT EXISTS (SELECT TG2.MADT
													FROM THAMGIADT AS TG2 JOIN GIAOVIEN AS GV2 ON (GV2.MAGV = TG2.MAGV)
													WHERE GV2.HOTEN = N'Trần Trà Hương'
												EXCEPT
												   (SELECT TG3.MADT
													 FROM THAMGIADT AS TG3 
													 WHERE TG3.MAGV = TG1.MAGV))

-- NOT EXISTS
SELECT DISTINCT GV.HOTEN
FROM DETAI AS DT JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT.MADT) JOIN  GIAOVIEN AS GV ON (GV.MAGV = TG1.MAGV)
WHERE GV.HOTEN != N'Trần Trà Hương' 
	AND NOT EXISTS (SELECT TG2.*
					FROM THAMGIADT AS TG2 JOIN GIAOVIEN AS GV2 ON (GV2.MAGV = TG2.MAGV)
					WHERE GV2.HOTEN = N'Trần Trà Hương' 
						AND NOT EXISTS (SELECT TG3.* 
										FROM THAMGIADT AS TG3 
										WHERE TG3.MADT = TG2.MADT AND TG3.MAGV = TG1.MAGV))
-- COUNT
SELECT GV.HOTEN 
-- lấy bảng mà các đề tài của TTH tham gia join với bảng TGDT
FROM (SELECT MADT AS SMADT
		FROM THAMGIADT JOIN GIAOVIEN ON (THAMGIADT.MAGV = GIAOVIEN.MAGV)
		WHERE GIAOVIEN.HOTEN = N'Trần Trà Hương') AS T JOIN THAMGIADT AS TG1 ON (TG1.MADT = T.SMADT) 
			JOIN GIAOVIEN AS GV ON (GV.MAGV = TG1.MAGV)
WHERE GV.HOTEN != N'Trần Trà Hương' 
GROUP BY TG1.MAGV, GV.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) =  (SELECT COUNT(DISTINCT TG2.MADT) 
									  FROM THAMGIADT AS TG2 JOIN GIAOVIEN AS GV2 ON (GV2.MAGV = TG2.MAGV)
									  WHERE GV2.HOTEN = N'Trần Trà Hương' )

--Q63. Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn Hóa Hữu Cơ tham gia.

--EXCEPT
SELECT DISTINCT DT.TENDT
FROM DETAI AS DT JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT.MADT) 
	JOIN GIAOVIEN AS GV ON (GV.MAGV = TG1.MAGV) 
	JOIN BOMON AS BM ON (BM.MABM = GV.MABM)
WHERE BM.TENBM = N'Hệ thống thông tin'  AND NOT EXISTS (SELECT GV2.MAGV
												FROM GIAOVIEN AS GV2 JOIN BOMON AS BM2 ON (BM2.MABM = GV2.MABM)
												WHERE BM2.TENBM = N'Hệ thống thông tin' 
											EXCEPT 
											  SELECT TG3.MAGV
												FROM THAMGIADT AS TG3 
												WHERE TG3.MADT = TG1.MADT)


-- NOT EXISTS
SELECT DISTINCT DT.TENDT
FROM DETAI AS DT JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT.MADT) 
	JOIN GIAOVIEN AS GV ON (GV.MAGV = TG1.MAGV) 
	JOIN BOMON AS BM ON (BM.MABM = GV.MABM)
WHERE BM.TENBM = N'Hóa hữu cơ'  AND NOT EXISTS (SELECT TG2.MADT
												FROM THAMGIADT AS TG2 JOIN GIAOVIEN AS GV2 ON (GV2.MAGV = TG2.MAGV) 
													JOIN BOMON AS BM2 ON (BM2.MABM = GV2.MABM)
												WHERE BM2.TENBM = N'Hóa hữu cơ'  AND 
											NOT EXISTS(
											  SELECT TG3.MADT
												FROM THAMGIADT AS TG3 
												WHERE TG3.MADT = TG1.MADT AND TG3.MADT = TG2.MADT))

-- COUNT
SELECT DISTINCT DT.TENDT
FROM DETAI AS DT JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT.MADT) 
	JOIN GIAOVIEN AS GV ON (GV.MAGV = TG1.MAGV) 
	JOIN BOMON AS BM ON (BM.MABM = GV.MABM)
WHERE BM.TENBM = N'Hóa hữu cơ'  
GROUP BY DT.TENDT, DT.MADT
HAVING COUNT (DISTINCT GV.MAGV) = (SELECT COUNT (GV2.MAGV)
									FROM GIAOVIEN AS GV2 JOIN BOMON AS BM2 ON (BM2.MABM = GV2.MABM)
									WHERE BM2.TENBM = N'Hóa hữu cơ' )


-- Q64. Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài 006.

-- EXCEPT
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN AS GV1 JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV1.MAGV) 
	JOIN CONGVIEC AS CV1 ON (CV1.MADT =TG1.MADT AND CV1.SOTT = TG1.STT)
WHERE TG1.MADT = '006' AND NOT EXISTS (SELECT CV2.SOTT, CV2.MADT
										FROM CONGVIEC AS CV2 
										WHERE CV2.MADT = '006'
									EXCEPT 
									   SELECT CV3.SOTT, CV3.MADT
										FROM CONGVIEC AS CV3 JOIN THAMGIADT AS TG2 ON (TG2.MADT = CV3.MADT AND CV3.SOTT = TG2.STT)
										WHERE TG1.MAGV = TG2.MAGV)

-- NOT EXIST
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN AS GV1 JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV1.MAGV) 
	JOIN CONGVIEC AS CV1 ON (CV1.MADT =TG1.MADT AND CV1.SOTT = TG1.STT)
WHERE TG1.MADT = '006' AND NOT EXISTS (SELECT CV2.SOTT, CV2.MADT
										FROM CONGVIEC AS CV2 
										WHERE CV2.MADT = '006' AND 
									NOT EXISTS(									 
									   SELECT CV3.SOTT, CV3.MADT
										FROM CONGVIEC AS CV3 JOIN THAMGIADT AS TG2 ON (TG2.MADT = CV3.MADT AND CV3.SOTT = TG2.STT)
										WHERE TG1.MAGV = TG2.MAGV AND CV3.MADT = CV2.MADT AND CV3.SOTT = CV2.SOTT))

-- COUNT 
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN AS GV1 JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV1.MAGV) 
	JOIN CONGVIEC AS CV1 ON (CV1.MADT =TG1.MADT AND CV1.SOTT = TG1.STT)
WHERE TG1.MADT = '006' 
GROUP BY GV1.HOTEN, TG1.MAGV, TG1.MADT
HAVING COUNT (TG1.STT) = (SELECT COUNT(SOTT)
							FROM CONGVIEC 
							WHERE MADT = '006')

-- Q65. Cho biết giáo viên nào đã tham gia tất cả các đề tài của chủ đề Ứng dụng công nghệ

-- EXCEPT
SELECT DISTINCT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN AS GV1 JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV1.MAGV) 
	JOIN DETAI AS DT1 ON (DT1.MADT = TG1.MADT) 
	JOIN CHUDE AS CD1 ON (CD1.MACD = DT1.MACD)
WHERE CD1.TENCD = N'Ứng dụng công nghệ' AND 
			NOT EXISTS (SELECT DT2.MADT
						 FROM DETAI AS DT2 JOIN CHUDE AS CD2 ON (CD2.MACD = DT2.MACD)
						 WHERE CD2.TENCD = N'Ứng dụng công nghệ'
					EXCEPT
						SELECT TG2.MADT
						 FROM THAMGIADT AS TG2 
						 WHERE TG2.MAGV = TG1.MAGV)

-- NOT EXISTS
SELECT DISTINCT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN AS GV1 JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV1.MAGV) 
	JOIN DETAI AS DT1 ON (DT1.MADT = TG1.MADT) 
	JOIN CHUDE AS CD1 ON (CD1.MACD = DT1.MACD)
WHERE CD1.TENCD = N'Ứng dụng công nghệ' AND 
			NOT EXISTS (SELECT DT2.MADT
						 FROM DETAI AS DT2 JOIN CHUDE AS CD2 ON (CD2.MACD = DT2.MACD)
						 WHERE CD2.TENCD = N'Ứng dụng công nghệ' 
					AND NOT EXISTS(
						SELECT TG2.MADT
						 FROM THAMGIADT AS TG2 
						 WHERE TG2.MAGV = TG1.MAGV AND TG2.MADT = DT2.MADT))

-- COUNT
SELECT DISTINCT GV1.MAGV, GV1.HOTEN
FROM GIAOVIEN AS GV1 JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV1.MAGV) 
	JOIN DETAI AS DT1 ON (DT1.MADT = TG1.MADT) 
	JOIN CHUDE AS CD1 ON (CD1.MACD = DT1.MACD)
WHERE CD1.TENCD = N'Ứng dụng công nghệ' 
GROUP BY GV1.MAGV, GV1.HOTEN
HAVING COUNT(DISTINCT TG1.MADT) = (SELECT COUNT (DT2.MADT)
									FROM DETAI AS DT2 JOIN CHUDE AS CD2 ON (CD2.MACD = DT2.MACD)
									WHERE CD2.TENCD = N'Ứng dụng công nghệ')

-- Q66. Cho biết tên giáo viên nào đã tham gia tất cả các đề tài của do Trần Trà Hương làm chủ nhiệm

SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV.MAGV) 
	JOIN DETAI AS DT ON (DT.MADT = TG1.MADT) 
	JOIN GIAOVIEN AS GVCN ON (GVCN.MAGV = DT.GVCNDT)
WHERE GVCN.HOTEN = N'Trần Trà Hương' 
		AND NOT EXISTS (SELECT TG2.MADT
						 FROM THAMGIADT AS TG2 JOIN DETAI AS DT2 ON (DT2.MADT = TG2.MADT) 
							JOIN GIAOVIEN AS GVCN2 ON (GVCN2.MAGV = DT2.GVCNDT)
						 WHERE GVCN2.HOTEN = N'Trần Trà Hương'
					EXCEPT
						SELECT TG3.MADT
						 FROM THAMGIADT AS TG3 
						 WHERE TG3.MAGV = TG1.MAGV)

SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV.MAGV) 
	JOIN DETAI AS DT ON (DT.MADT = TG1.MADT) 
	JOIN GIAOVIEN AS GVCN ON (GVCN.MAGV = DT.GVCNDT)
WHERE GVCN.HOTEN = N'Trần Trà Hương' 
		AND NOT EXISTS (SELECT TG2.MADT
						 FROM THAMGIADT AS TG2 JOIN DETAI AS DT2 ON (DT2.MADT = TG2.MADT) 
							JOIN GIAOVIEN AS GVCN2 ON (GVCN2.MAGV = DT2.GVCNDT)
						 WHERE GVCN2.HOTEN = N'Trần Trà Hương'
					AND NOT EXISTS(
						SELECT TG3.MADT
						 FROM THAMGIADT AS TG3 
						 WHERE TG3.MAGV = TG1.MAGV AND TG3.MADT = TG2.MADT))

SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV.MAGV) 
	JOIN DETAI AS DT ON (DT.MADT = TG1.MADT) 
	JOIN GIAOVIEN AS GVCN ON (GVCN.MAGV = DT.GVCNDT)
WHERE GVCN.HOTEN = N'Trần Trà Hương' 
GROUP BY TG1.MAGV, GV.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) = (SELECT COUNT (DETAI.MADT)
									FROM  DETAI JOIN GIAOVIEN ON (GIAOVIEN.MAGV = DETAI.GVCNDT)
									WHERE GIAOVIEN.HOTEN = N'Trần Trà Hương')

-- Q67. Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa CNTT tham gia.

SELECT DISTINCT DT1.TENDT
FROM DETAI AS DT1 JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT1.MADT) 
	JOIN GIAOVIEN AS GV1 ON (GV1.MAGV = TG1.MAGV) 
	JOIN BOMON AS BM1 ON (BM1.MABM = GV1.MABM) 
WHERE BM1.MAKHOA = 'CNTT' AND NOT EXISTS (SELECT TG2.MAGV
										   FROM THAMGIADT AS TG2 JOIN GIAOVIEN AS GV2 ON (GV2.MAGV = TG2.MAGV) 
											JOIN BOMON AS BM2 ON (BM2.MABM = GV2.MABM) 
										   WHERE BM2.MAKHOA = 'CNTT'
										EXCEPT 
										  SELECT TG3.MAGV
										   FROM THAMGIADT AS TG3
										   WHERE TG3.MADT = TG1.MADT)

-- NOT EXISTS
SELECT DISTINCT DT1.TENDT
FROM DETAI AS DT1 JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT1.MADT) 
	JOIN GIAOVIEN AS GV1 ON (GV1.MAGV = TG1.MAGV) 
	JOIN BOMON AS BM1 ON (BM1.MABM = GV1.MABM) 
WHERE BM1.MAKHOA = 'CNTT' AND NOT EXISTS (SELECT TG2.MAGV
										   FROM THAMGIADT AS TG2 JOIN GIAOVIEN AS GV2 ON (GV2.MAGV = TG2.MAGV) 
												JOIN BOMON AS BM2 ON (BM2.MABM = GV2.MABM) 
										   WHERE BM2.MAKHOA = 'CNTT'
										AND NOT EXISTS( 
										  SELECT TG3.MAGV
										   FROM THAMGIADT AS TG3
										   WHERE TG3.MADT = TG1.MADT AND TG3.MAGV = TG2.MAGV))

-- COUNT
SELECT DISTINCT DT1.TENDT
FROM DETAI AS DT1 JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT1.MADT) 
	JOIN GIAOVIEN AS GV1 ON (GV1.MAGV = TG1.MAGV) 
	JOIN BOMON AS BM1 ON (BM1.MABM = GV1.MABM) 
WHERE BM1.MAKHOA = 'CNTT' 
GROUP BY DT1.MADT, DT1.TENDT
HAVING COUNT (DISTINCT TG1.MAGV) = (SELECT COUNT(GIAOVIEN.MAGV)
									FROM GIAOVIEN JOIN BOMON ON (BOMON.MABM = GIAOVIEN.MABM) 
									WHERE BOMON.MAKHOA = 'CNTT')

-- Q68. Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài Nghiên cứu tế bào gốc.

-- EXCEPT
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN AS GV1 JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV1.MAGV) 
	JOIN DETAI AS DT1 ON (DT1.MADT = TG1.MADT) 
	JOIN CONGVIEC AS CV1 ON (CV1.MADT = DT1.MADT AND CV1.SOTT = TG1.STT)
WHERE DT1.TENDT = N'Nghiên cứu tế bào gốc'  
	AND NOT EXISTS (SELECT CV2.SOTT, CV2.MADT
					FROM CONGVIEC AS CV2 JOIN DETAI AS DT2 ON (DT2.MADT = CV2.MADT)
					WHERE DT2.TENDT = N'Nghiên cứu tế bào gốc'
				EXCEPT 
					SELECT CV3.SOTT, CV3.MADT
					FROM CONGVIEC AS CV3 JOIN THAMGIADT AS TG2 ON (TG2.MADT = CV3.MADT AND TG2.STT = CV3.SOTT)
					WHERE TG2.MAGV = TG1.MAGV)

-- NOT EXISTS
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN AS GV1 JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV1.MAGV) 
	JOIN DETAI AS DT1 ON (DT1.MADT = TG1.MADT) 
	JOIN CONGVIEC AS CV1 ON (CV1.MADT = DT1.MADT AND CV1.SOTT = TG1.STT)
WHERE DT1.TENDT = N'Nghiên cứu tế bào gốc'  
	AND NOT EXISTS (SELECT CV2.SOTT, CV2.MADT
					FROM CONGVIEC AS CV2 JOIN DETAI AS DT2 ON (DT2.MADT = CV2.MADT)
					WHERE DT2.TENDT = N'Nghiên cứu tế bào gốc'
				AND NOT EXISTS ( 
					SELECT CV3.SOTT, CV3.MADT
					FROM CONGVIEC AS CV3 JOIN THAMGIADT AS TG2 ON (TG2.MADT = CV3.MADT AND TG2.STT = CV3.SOTT)
					WHERE TG2.MAGV = TG1.MAGV AND CV2.SOTT = CV3.SOTT AND CV2.MADT = CV3.MADT))

-- COUNT
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN AS GV1 JOIN THAMGIADT AS TG1 ON (TG1.MAGV = GV1.MAGV) 
	JOIN DETAI AS DT1 ON (DT1.MADT = TG1.MADT) 
	JOIN CONGVIEC AS CV1 ON (CV1.MADT = DT1.MADT AND CV1.SOTT = TG1.STT)
WHERE DT1.TENDT = N'Nghiên cứu tế bào gốc' 
GROUP BY GV1.MAGV, GV1.HOTEN, TG1.MADT
HAVING COUNT(TG1.STT) = (SELECT COUNT (CV2.SOTT)
						 FROM CONGVIEC AS CV2 JOIN DETAI AS DT2 ON (DT2.MADT = CV2.MADT)
						 WHERE DT2.TENDT = N'Nghiên cứu tế bào gốc')

-- Q69. Tìm tên các giáo viên được phân công làm tất cả các đề tài có kinh phí trên 100 triệu?

SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN GV1 JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV) 
	JOIN DETAI DT1 ON (DT1.MADT = TG1.MADT)
WHERE DT1.KINHPHI > 100 
	AND NOT EXISTS ( SELECT DT2.MADT
					FROM DETAI DT2 
					WHERE DT2.KINHPHI >100
				EXCEPT 
					SELECT DT3.MADT
					FROM DETAI DT3 JOIN THAMGIADT TG2 ON (TG2.MADT = DT3.MADT)
					WHERE TG2.MAGV = TG1.MAGV)

-- NOT EXISTS
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN GV1 JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV) 
	JOIN DETAI DT1 ON (DT1.MADT = TG1.MADT)
WHERE DT1.KINHPHI > 100 AND NOT EXISTS (SELECT DT2.MADT
										FROM DETAI DT2 
										WHERE DT2.KINHPHI >100
									AND NOT EXISTS (
										SELECT DT3.MADT
										FROM DETAI DT3 JOIN THAMGIADT TG2 ON (TG2.MADT = DT3.MADT)
										WHERE TG2.MAGV = TG1.MAGV AND DT2.MADT = DT3.MADT))

-- COUNT
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN GV1 JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV) 
	JOIN DETAI DT1 ON (DT1.MADT = TG1.MADT)
WHERE DT1.KINHPHI > 100 
GROUP BY GV1.HOTEN, TG1.MAGV
HAVING COUNT (DISTINCT TG1.MADT) = (SELECT COUNT(MADT)
									FROM DETAI 
									WHERE DETAI.KINHPHI >100)

-- Q70. Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa Sinh Học tham gia.
-- EXCEPT
SELECT DISTINCT DT1.TENDT
FROM DETAI AS DT1 JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT1.MADT) 
	JOIN GIAOVIEN AS GV1 ON (GV1.MAGV = TG1.MAGV)
	JOIN BOMON AS BM1 ON (BM1.MABM = GV1.MABM) 
	JOIN KHOA K1 ON (K1.MAKHOA = BM1.MAKHOA)
WHERE K1.TENKHOA = N'Sinh học' AND NOT EXISTS (SELECT TG2.MAGV
												FROM THAMGIADT AS TG2 JOIN GIAOVIEN AS GV2 ON (GV2.MAGV = TG2.MAGV)
													JOIN BOMON AS BM2 ON (BM2.MABM = GV2.MABM) 
													JOIN KHOA K2 ON (K2.MAKHOA = BM2.MAKHOA)
												WHERE K2.TENKHOA = N'Sinh học'
											EXCEPT 
												SELECT TG3.MAGV
												FROM THAMGIADT AS TG3
												WHERE TG3.MADT = TG1.MADT)

-- NOT EXISTS
SELECT DISTINCT DT1.TENDT
FROM DETAI AS DT1 JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT1.MADT) 
	JOIN GIAOVIEN AS GV1 ON (GV1.MAGV = TG1.MAGV)
	JOIN BOMON AS BM1 ON (BM1.MABM = GV1.MABM) 
	JOIN KHOA K1 ON (K1.MAKHOA = BM1.MAKHOA)
WHERE K1.TENKHOA = N'Sinh học' AND NOT EXISTS (SELECT TG2.MAGV
												FROM THAMGIADT AS TG2 JOIN GIAOVIEN AS GV2 ON (GV2.MAGV = TG2.MAGV)
													JOIN BOMON AS BM2 ON (BM2.MABM = GV2.MABM) 
													JOIN KHOA K2 ON (K2.MAKHOA = BM2.MAKHOA)
												WHERE K2.TENKHOA = N'Sinh học'
											AND NOT EXISTS( 
												SELECT TG3.MAGV
												FROM THAMGIADT AS TG3
												WHERE TG3.MADT = TG1.MADT AND TG3.MAGV = TG2.MAGV))

-- COUNT
SELECT DISTINCT DT1.TENDT
FROM DETAI AS DT1 JOIN THAMGIADT AS TG1 ON (TG1.MADT = DT1.MADT) 
	JOIN GIAOVIEN AS GV1 ON (GV1.MAGV = TG1.MAGV)
	JOIN BOMON AS BM1 ON (BM1.MABM = GV1.MABM) 
	JOIN KHOA K1 ON (K1.MAKHOA = BM1.MAKHOA)
WHERE K1.TENKHOA = N'Sinh học' 
GROUP BY DT1.TENDT, TG1.MADT
HAVING COUNT(DISTINCT TG1.MAGV) = (SELECT COUNT (GV.MAGV)
									FROM GIAOVIEN GV JOIN BOMON BM ON (BM.MABM = GV.MABM) JOIN KHOA K ON (K.MAKHOA = BM.MAKHOA)
									WHERE K.TENKHOA = N'Sinh học')


-- Q71. Cho biết mã số, họ tên, ngày sinh của giáo viên tham gia tất cả các công việc của đề tài “Ứng dụng hóa học xanh”
-- bị chia: công việc của đề tài "Ứng dụng hóa học xanh"
-- EXCEPT
SELECT DISTINCT GV1.MAGV, GV1.HOTEN, GV1.NGAYSINH
FROM GIAOVIEN GV1 JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV)
	JOIN DETAI DT1 ON (DT1.MADT = TG1.MADT)
	JOIN CONGVIEC CV1 ON (CV1.MADT = TG1.MADT AND TG1.STT = CV1.SOTT)
WHERE DT1.TENDT = N'Ứng dụng hóa học xanh' 
	AND NOT EXISTS (SELECT CV2.MADT, CV2.SOTT
					FROM CONGVIEC CV2 JOIN DETAI DT2 ON (DT2.MADT = CV2.MADT) 
					WHERE DT2.TENDT = N'Ứng dụng hóa học xanh' 
				EXCEPT 
					SELECT TG2.MADT, TG2.STT
					FROM THAMGIADT TG2 
					WHERE TG2.MAGV = TG1.MAGV)
					
-- NOT EXISTS
SELECT DISTINCT GV1.MAGV, GV1.HOTEN, GV1.NGAYSINH
FROM GIAOVIEN GV1 JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV)
	JOIN DETAI DT1 ON (DT1.MADT = TG1.MADT)
	JOIN CONGVIEC CV1 ON (CV1.MADT = TG1.MADT AND TG1.STT = CV1.SOTT)
WHERE DT1.TENDT = N'Ứng dụng hóa học xanh' 
	AND NOT EXISTS (SELECT CV2.MADT, CV2.SOTT
					FROM CONGVIEC CV2 JOIN DETAI DT2 ON (DT2.MADT = CV2.MADT) 
					WHERE DT2.TENDT = N'Ứng dụng hóa học xanh' 
				AND NOT EXISTS (
					SELECT TG2.MADT, TG2.STT
					FROM THAMGIADT TG2 
					WHERE TG2.MAGV = TG1.MAGV AND TG2.MADT = CV2.MADT AND TG2.STT = CV2.SOTT))

-- COUNT
SELECT DISTINCT GV1.MAGV, GV1.HOTEN, GV1.NGAYSINH
FROM GIAOVIEN GV1 JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV)
	JOIN DETAI DT1 ON (DT1.MADT = TG1.MADT)
	JOIN CONGVIEC CV1 ON (CV1.MADT = TG1.MADT AND TG1.STT = CV1.SOTT)
WHERE DT1.TENDT = N'Ứng dụng hóa học xanh'  
GROUP BY GV1.MAGV, GV1.HOTEN, GV1.NGAYSINH, TG1.MADT
HAVING COUNT (TG1.STT) = (SELECT COUNT(SOTT)
							FROM CONGVIEC CV2 JOIN DETAI DT2 ON (DT2.MADT = CV2.MADT)
							WHERE DT2.TENDT = N'Ứng dụng hóa học xanh')

-- Q72. Cho biết mã số, họ tên, tên bộ môn và tên người quản lý chuyên môn của giáo viên tham gia tất cả các đề tài thuộc chủ đề “Nghiên cứu phát triển”.
-- bị chia: đề tài thuộc chủ đề 'Nghiên cứu phát triển'
-- EXCEPT
SELECT DISTINCT GV1.MAGV, GV1.HOTEN, BM1.TENBM, GVQL.HOTEN
FROM GIAOVIEN GV1 LEFT JOIN GIAOVIEN GVQL ON (GV1.GVQLCM = GVQL.MAGV) 
	JOIN BOMON BM1 ON (BM1.MABM = GV1.MABM) 
	JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV)
	JOIN DETAI DT1 ON (DT1.MADT = TG1.MADT)
	JOIN CHUDE CD1 ON (CD1.MACD = DT1.MACD)
WHERE CD1.TENCD = N'Nghiên cứu phát triển' 
	AND NOT EXISTS (SELECT DT2.MADT
					FROM DETAI DT2 JOIN CHUDE CD2 ON (CD2.MACD = DT2.MACD)
					WHERE CD2.TENCD = N'Nghiên cứu phát triển'
				EXCEPT
					SELECT TG2.MADT
					FROM THAMGIADT TG2 
					WHERE TG2.MAGV = TG1.MAGV)

-- NOT EXISTS
SELECT DISTINCT GV1.MAGV, GV1.HOTEN, BM1.TENBM, GVQL.HOTEN AS GVQLCM_HOTEN
FROM GIAOVIEN GV1 LEFT JOIN GIAOVIEN GVQL ON (GV1.GVQLCM = GVQL.MAGV) 
	JOIN BOMON BM1 ON (BM1.MABM = GV1.MABM) 
	JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV)
	JOIN DETAI DT1 ON (DT1.MADT = TG1.MADT)
	JOIN CHUDE CD1 ON (CD1.MACD = DT1.MACD)
WHERE CD1.TENCD = N'Nghiên cứu phát triển' 
	AND NOT EXISTS (SELECT DT2.MADT
					FROM DETAI DT2 JOIN CHUDE CD2 ON (CD2.MACD = DT2.MACD)
					WHERE CD2.TENCD = N'Nghiên cứu phát triển'
				EXCEPT
					SELECT TG2.MADT
					FROM THAMGIADT TG2 
					WHERE TG2.MAGV = TG1.MAGV)

-- NOT EXIST
SELECT DISTINCT GV1.MAGV, GV1.HOTEN, BM1.TENBM, GVQL.HOTEN AS GVQLCM_HOTEN
FROM GIAOVIEN GV1 LEFT JOIN GIAOVIEN GVQL ON (GV1.GVQLCM = GVQL.MAGV) 
	JOIN BOMON BM1 ON (BM1.MABM = GV1.MABM) 
	JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV)
	JOIN DETAI DT1 ON (DT1.MADT = TG1.MADT)
	JOIN CHUDE CD1 ON (CD1.MACD = DT1.MACD)
WHERE CD1.TENCD = N'Nghiên cứu phát triển' 
	AND NOT EXISTS (SELECT DT2.MADT
					FROM DETAI DT2 JOIN CHUDE CD2 ON (CD2.MACD = DT2.MACD)
					WHERE CD2.TENCD = N'Nghiên cứu phát triển'
			AND NOT EXISTS (
					SELECT TG2.MADT
					FROM THAMGIADT TG2 
					WHERE TG2.MAGV = TG1.MAGV AND DT2.MADT = TG2.MADT))

-- COUNT
SELECT DISTINCT GV1.MAGV, GV1.HOTEN, BM1.TENBM, GVQL.HOTEN AS GVQLCM_HOTEN
FROM GIAOVIEN GV1 LEFT JOIN GIAOVIEN GVQL ON (GV1.GVQLCM = GVQL.MAGV) 
	JOIN BOMON BM1 ON (BM1.MABM = GV1.MABM) 
	JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV)
	JOIN DETAI DT1 ON (DT1.MADT = TG1.MADT)
	JOIN CHUDE CD1 ON (CD1.MACD = DT1.MACD)
WHERE CD1.TENCD = N'Nghiên cứu phát triển' 
GROUP BY GV1.MAGV, GV1.HOTEN, BM1.TENBM, GVQL.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) = (SELECT COUNT(DT2.MADT)
									FROM DETAI DT2 JOIN CHUDE CD2 ON (CD2.MACD = DT2.MACD)
									WHERE CD2.TENCD = N'Nghiên cứu phát triển')


-- Q73. Cho biết họ tên, ngày sinh, tên khoa, tên trưởng khoa của giáo viên tham gia tất cả các đế̀ tài có giáo viên “Nguyế̃n Hoài An” tham gia.
-- bị chia: các đề tài có 'Nguyễn Hoài An' tham gia
SELECT DISTINCT GV1.HOTEN, GV1.NGAYSINH, K1.TENKHOA, TRUONGKHOA.HOTEN AS TRUONGKHOA_HOTEN
FROM GIAOVIEN GV1 JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV)
	JOIN BOMON BM1 ON (BM1.MABM = GV1.MABM) 
	JOIN KHOA K1 ON (K1.MAKHOA = BM1.MAKHOA)
	JOIN GIAOVIEN TRUONGKHOA ON (TRUONGKHOA.MAGV = K1.TRUONGKHOA)
WHERE GV1.HOTEN != N'Nguyễn Hoài An' 
	AND NOT EXISTS (SELECT TG2.MADT
					FROM THAMGIADT TG2 JOIN GIAOVIEN GV2 ON (GV2.MAGV = TG2.MAGV)
					WHERE GV2.HOTEN = N'Nguyễn Hoài An' 
				EXCEPT 
					SELECT TG3.MADT
					FROM THAMGIADT TG3
					WHERE TG3.MAGV = TG1.MAGV)

-- NOT EXISTS
SELECT DISTINCT GV1.HOTEN, GV1.NGAYSINH, K1.TENKHOA, TRUONGKHOA.HOTEN AS TRUONGKHOA_HOTEN
FROM GIAOVIEN GV1 JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV)
	JOIN BOMON BM1 ON (BM1.MABM = GV1.MABM) 
	JOIN KHOA K1 ON (K1.MAKHOA = BM1.MAKHOA)
	JOIN GIAOVIEN TRUONGKHOA ON (TRUONGKHOA.MAGV = K1.TRUONGKHOA)
WHERE GV1.HOTEN != N'Nguyễn Hoài An' 
	AND NOT EXISTS (SELECT TG2.MADT
					FROM THAMGIADT TG2 JOIN GIAOVIEN GV2 ON (GV2.MAGV = TG2.MAGV)
					WHERE GV2.HOTEN = N'Nguyễn Hoài An' 
				AND NOT EXISTS( 
					SELECT TG3.MADT
					FROM THAMGIADT TG3
					WHERE TG3.MAGV = TG1.MAGV AND TG3.MADT = TG2.MADT))

-- COUNT
SELECT DISTINCT GV1.HOTEN, GV1.NGAYSINH, K1.TENKHOA, TRUONGKHOA.HOTEN AS TRUONGKHOA_HOTEN
FROM (SELECT MADT AS SMADT
		FROM THAMGIADT JOIN GIAOVIEN ON (THAMGIADT.MAGV = GIAOVIEN.MAGV)
		WHERE GIAOVIEN.HOTEN = N'Nguyễn Hoài An') AS MADT1
	JOIN THAMGIADT TG1 ON (TG1.MADT = MADT1.SMADT)
	JOIN GIAOVIEN GV1  ON (TG1.MAGV = GV1.MAGV)
	JOIN BOMON BM1 ON (BM1.MABM = GV1.MABM) 
	JOIN KHOA K1 ON (K1.MAKHOA = BM1.MAKHOA)
	JOIN GIAOVIEN TRUONGKHOA ON (TRUONGKHOA.MAGV = K1.TRUONGKHOA)
WHERE GV1.HOTEN != N'Nguyễn Hoài An'  
GROUP BY GV1.HOTEN, GV1.NGAYSINH, K1.TENKHOA, TRUONGKHOA.HOTEN
HAVING COUNT (DISTINCT TG1.MADT) = (SELECT COUNT(DISTINCT TG2.MADT) 
									  FROM THAMGIADT AS TG2 JOIN GIAOVIEN AS GV2 ON (GV2.MAGV = TG2.MAGV)
									  WHERE GV2.HOTEN = N'Nguyễn Hoài An')


-- Q74. Cho biết họ tên giáo viên khoa 'Công nghệ thông tin' tham gia tất cả công việc của đề tài có (trưởng bộ môn của bộ môn đông nhất khoa 'Công nghệ thông tin' làm chủ nhiệm)

-- EXCEPT
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN GV1 JOIN BOMON BM1 ON (GV1.MABM = BM1.MABM)
	JOIN KHOA K1 ON (K1.MAKHOA = BM1.MAKHOA)
	JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV)
WHERE K1.TENKHOA = N'Công nghệ thông tin' 
	AND NOT EXISTS (
					SELECT CV.SOTT, CV.MADT
					FROM DETAI DT JOIN CONGVIEC CV ON (CV.MADT = DT.MADT) 
						JOIN (
								SELECT TRUONGBM.MAGV 
								FROM GIAOVIEN GV JOIN BOMON BM ON (GV.MABM =BM.MABM)
									JOIN GIAOVIEN TRUONGBM ON (BM.TRUONGBM = TRUONGBM.MAGV) 
									JOIN KHOA K ON (K.MAKHOA = BM.MAKHOA)
								WHERE K.TENKHOA = N'Công nghệ thông tin' 
								GROUP BY BM.MABM, TRUONGBM.MAGV
								HAVING COUNT(GV.MAGV) = (SELECT MAX(SLGiaoVien)
														 FROM (SELECT COUNT(GV.MAGV) AS SLGiaoVien
																FROM GIAOVIEN GV JOIN BOMON BM ON (GV.MABM =BM.MABM)
																	JOIN GIAOVIEN TRUONGBM  ON (BM.TRUONGBM = TRUONGBM.MAGV) 
																	JOIN KHOA K ON (K.MAKHOA = BM.MAKHOA)
																WHERE K.TENKHOA = N'Công nghệ thông tin'  
																GROUP BY GV.MABM) AS T)) AS T2 ON (T2.MAGV = DT.GVCNDT)
				EXCEPT 
					SELECT TG3.STT, TG3.MADT
					FROM THAMGIADT TG3
					WHERE TG3.MAGV = TG1.MAGV)
		

-- NOT EXISTS
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN GV1 JOIN BOMON BM1 ON (GV1.MABM = BM1.MABM)
	JOIN KHOA K1 ON (K1.MAKHOA = BM1.MAKHOA)
	JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV)
WHERE K1.TENKHOA = N'Công nghệ thông tin' 
	AND NOT EXISTS ( 
					SELECT CV.SOTT, CV.MADT
					FROM DETAI DT JOIN CONGVIEC CV ON (CV.MADT = DT.MADT) 
						JOIN (
								SELECT TRUONGBM.MAGV 
								FROM GIAOVIEN GV JOIN BOMON BM ON (GV.MABM =BM.MABM)
									JOIN GIAOVIEN TRUONGBM ON (BM.TRUONGBM = TRUONGBM.MAGV) 
									JOIN KHOA K ON (K.MAKHOA = BM.MAKHOA)
								WHERE K.TENKHOA = N'Công nghệ thông tin' 
								GROUP BY BM.MABM, TRUONGBM.MAGV
								HAVING COUNT(GV.MAGV) = (SELECT MAX(SLGiaoVien)
														 FROM (SELECT COUNT(GV.MAGV) AS SLGiaoVien
																FROM GIAOVIEN GV JOIN BOMON BM ON (GV.MABM =BM.MABM)
																	JOIN GIAOVIEN TRUONGBM  ON (BM.TRUONGBM = TRUONGBM.MAGV) 
																	JOIN KHOA K ON (K.MAKHOA = BM.MAKHOA)
																WHERE K.TENKHOA = N'Công nghệ thông tin'  
																GROUP BY GV.MABM) AS T)) AS T2 ON (T2.MAGV = DT.GVCNDT)
					WHERE NOT EXISTS (
										SELECT TG3.STT, TG3.MADT
										FROM THAMGIADT TG3
										WHERE TG3.MAGV = TG1.MAGV AND TG3.STT = CV.SOTT AND TG3.MADT = CV.MADT))

-- COUNT
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN GV1 JOIN BOMON BM1 ON (GV1.MABM = BM1.MABM)
	JOIN KHOA K1 ON (K1.MAKHOA = BM1.MAKHOA)
	JOIN THAMGIADT TG1 ON (TG1.MAGV = GV1.MAGV)
	JOIN DETAI DT1 ON (DT1.MADT = TG1.MADT) 
	JOIN
	(	SELECT TRUONGBM.MAGV 
						FROM GIAOVIEN GV JOIN BOMON BM ON (GV.MABM =BM.MABM)
							JOIN GIAOVIEN TRUONGBM ON (BM.TRUONGBM = TRUONGBM.MAGV) 
							JOIN KHOA K ON (K.MAKHOA = BM.MAKHOA)
						WHERE K.TENKHOA = N'Công nghệ thông tin' 
						GROUP BY BM.MABM, TRUONGBM.MAGV
						HAVING COUNT(GV.MAGV) = (SELECT MAX(SLGiaoVien)
												 FROM (SELECT COUNT(GV.MAGV) AS SLGiaoVien
														FROM GIAOVIEN GV JOIN BOMON BM ON (GV.MABM =BM.MABM)
															JOIN GIAOVIEN TRUONGBM  ON (BM.TRUONGBM = TRUONGBM.MAGV) 
															JOIN KHOA K ON (K.MAKHOA = BM.MAKHOA)
														WHERE K.TENKHOA = N'Công nghệ thông tin'  
														GROUP BY GV.MABM) AS T)) AS T2 ON (T2.MAGV = DT1.GVCNDT)
WHERE K1.TENKHOA = N'Công nghệ thông tin'  
GROUP BY TG1.MAGV, GV1.HOTEN, TG1.MADT
HAVING COUNT(TG1.STT) = (SELECT COUNT (CONGVIEC.SOTT)
						 FROM CONGVIEC 
						 WHERE CONGVIEC.MADT = TG1.MADT
						 GROUP BY CONGVIEC.MADT)


