-- MSSV: 21127090 
-- Mã đề: Đề 1

CREATE DATABASE QLTrungTam;
GO

USE QLTrungTam;
GO

CREATE TABLE HOIVIEN(
	MaHV VARCHAR(10),
	HoTen NVARCHAR(50),
	NgaySinh VARCHAR(50),
	DiaChi NVARCHAR(50),
	MaLoai NVARCHAR(10),
	NguoiGioiThieu VARCHAR(10),
	PRIMARY KEY (MaHV)
)

CREATE TABLE TRUNGTAM(
	MaCty VARCHAR(10),
	STT VARCHAR(10),
	DiaChi NVARCHAR(50),
	HoiTruong VARCHAR(10),
	NgayLap VARCHAR(50),
	PRIMARY KEY (MaCty, STT),
)

CREATE TABLE DANGKY(
	MaHV VARCHAR(10) UNIQUE,
	MaCty VARCHAR(10),
	MaTT VARCHAR(10),
	NgayDangKy VARCHAR(50),
	PhiDK FLOAT,
	ThoiHan INT,
	PRIMARY KEY (MaHV, MaCty, MaTT)
)

ALTER TABLE HOIVIEN
	ADD CONSTRAINT FK_NguoiGT_MaHV
	FOREIGN KEY (NguoiGioiThieu)
	REFERENCES HOIVIEN(MaHV)

ALTER TABLE TRUNGTAM
	ADD CONSTRAINT FK_TRUNGTAM_HOIVIEN
	FOREIGN KEY (HoiTruong) 
	REFERENCES HOIVIEN(MaHV)

ALTER TABLE DANGKY
	ADD CONSTRAINT FK_DANGKY_TRUNGTAM
	FOREIGN KEY(MaCty, MaTT) 
	REFERENCES TRUNGTAM(MaCty, STT)

INSERT INTO HOIVIEN(MaHV, HoTen, NgaySinh, DiaChi, MaLoai) VALUES ('HV01', N'Nguyễn Văn Sơn', '10/30/2000', N'1 Bis Nguyễn Trãi Q5 TP HCM', N'Bạc')
INSERT INTO HOIVIEN(MaHV, HoTen, NgaySinh, DiaChi, MaLoai) VALUES ('HV02', N'Trần Trung Kiên', '12/13/2000', N'12B Nguyễn Văn Trỗi Đồng Nai', N'Bạc')
INSERT INTO HOIVIEN(MaHV, HoTen, NgaySinh, MaLoai) VALUES ('HV03', N'Trần Thị Bình', '1/1/1998', N'Vàng')
INSERT INTO HOIVIEN(MaHV, HoTen, NgaySinh) VALUES ('HV04', N'Nguyễn Văn Toàn', '1/1/1978')

UPDATE HOIVIEN SET NguoiGioiThieu = 'HV03' WHERE MaHV = 'HV01'
UPDATE HOIVIEN SET NguoiGioiThieu = 'HV03' WHERE MaHV = 'HV02'
UPDATE HOIVIEN SET NguoiGioiThieu = 'HV01' WHERE MaHV = 'HV04'

INSERT INTO TRUNGTAM(MaCty, STT, HoiTruong, DiaChi, NgayLap) VALUES ('L1', '1', 'HV03', N'123 Vườn Lài, Tân Phú', '1/1/2022')
INSERT INTO TRUNGTAM(MaCty, STT, HoiTruong, DiaChi, NgayLap) VALUES ('L1', '2', 'HV03', N'45 Phú Thọ Hòa, Tân Phú', '12/13/2022')
INSERT INTO TRUNGTAM(MaCty, STT, HoiTruong, DiaChi, NgayLap) VALUES ('L2', '1', 'HV01', N'11 Võ Văn Ngân, Thủ Đức', '2/1/2023')

INSERT INTO DANGKY(MaCty, MaTT, MaHV, NgayDangKy, PhiDK, ThoiHan) VALUES ('L1', '1', 'HV01', '2/12/2009', 90000, 356)
INSERT INTO DANGKY(MaCty, MaTT, MaHV, NgayDangKy, PhiDK, ThoiHan) VALUES ('L1', '1', 'HV02', '12/30/2009', 87000, 500)
INSERT INTO DANGKY(MaCty, MaTT, MaHV, NgayDangKy, PhiDK, ThoiHan) VALUES ('L2', '1', 'HV03', '6/6/2016', 100000, 500)
INSERT INTO DANGKY(MaCty, MaTT, MaHV, NgayDangKy, PhiDK, ThoiHan) VALUES ('L1', '2', 'HV04', '3/7/2018', 120000, 100)

-- Q4
SELECT DISTINCT HOIVIEN.*
FROM HOIVIEN JOIN TRUNGTAM ON (HOIVIEN.MaHV = TRUNGTAM.HoiTruong AND TRUNGTAM.DiaChi LIKE N'% Tân Phú')

-- Q5
SELECT DANGKY.MaCty, DANGKY.MaTT AS STT, COUNT(MaHV) AS SLHoiVien
FROM DANGKY 
WHERE DATEDIFF(D,DANGKY.NgayDangKy, GETDATE()) <= DANGKY.ThoiHan
GROUP BY DANGKY.MaCty, DANGKY.MaTT


